language: rust

rust:
  - nightly
sudo: required
services:
  - docker
before_install:
  - docker run -dit --name emscripten -v $(pwd):/src alexfro/rust-wasm32-unknown-emscripten bash
script:
  - docker exec -it emscripten sh -c "cargo install --git https://github.com/paritytech/wasm-utils wasm-build"
  - docker exec -it emscripten sh -c "cargo install --git https://github.com/paritytech/parity/ pwasm-run-test --force"
  - docker exec -it emscripten sh -c "./build.sh"
  - docker exec -it emscripten sh -c "RUST_LOG=wasm=trace pwasm-run-test ./json/*.json"