[package]
name = "wasm-tests"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
wasm-std = { git = "https://github.com/nikvolf/wasm-std" }

[[bin]]
name = "empty"
path = "src/empty.rs"

[[bin]]
name = "suicidal"
path = "src/suicidal.rs"

[[bin]]
name = "realloc"
path = "src/realloc.rs"

[[bin]]
name = "logger"
path = "src/logger.rs"

[profile.release]
panic = "abort"